# Generated by Django 6.0.1 on 2026-01-13 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetadata',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LabFacility',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('organism_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhenotypeMetadata',
            fields=[
                ('phenotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingMetadata',
            fields=[
                ('sequencing_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SamplesMetadata',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('data_entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_samples', to=settings.AUTH_USER_MODEL)),
                ('facility_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_samples', to='projects.labfacility')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.hostmetadata')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.organism')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.phenotypemetadata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('referring_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_samples', to='projects.labfacility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_submissions', to=settings.AUTH_USER_MODEL)),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sampletype')),
                ('sequencing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sequencingmetadata')),
            ],
        ),
    ]
