# Generated by Django 6.0.1 on 2026-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status_alter_project_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
