# Generated by Django 6.0.1 on 2026-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_sample_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
