# Generated by Django 5.2.6 on 2026-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplesmetadata",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                editable=False,
                max_length=50,
                null=True,
            ),
        ),
    ]
