# Generated by Django 5.2.6 on 2026-01-20 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_samplesmetadata_review_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="samplesmetadata",
            name="ct_value",
            field=models.FloatField(
                blank=True, help_text="PCR cycle threshold value", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="drug_exposure_history",
            field=models.TextField(
                blank=True, help_text="Drugs and exposure timeline", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="isolate",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="life_stage",
            field=models.CharField(
                blank=True,
                help_text="e.g., trophozoite, gametocyte",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="parasite_density",
            field=models.FloatField(
                blank=True, help_text="Parasites per µL or specified unit", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="phenotype_notes",
            field=models.TextField(
                blank=True, help_text="Phenotypic observations and notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="propagation",
            field=models.CharField(
                blank=True,
                help_text="In vitro, in vivo, clinical",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="serotype",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="serotype_or_lineage",
            field=models.CharField(
                blank=True,
                help_text="Combined serotype or lineage",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="strain",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="samplesmetadata",
            name="viral_load",
            field=models.FloatField(
                blank=True, help_text="Viral copies per mL or specified unit", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="samplesmetadata",
            index=models.Index(
                fields=["serotype"], name="projects_sa_serotyp_fac530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="samplesmetadata",
            index=models.Index(fields=["strain"], name="projects_sa_strain_cd0833_idx"),
        ),
        migrations.AddIndex(
            model_name="samplesmetadata",
            index=models.Index(
                fields=["isolate"], name="projects_sa_isolate_8e2288_idx"
            ),
        ),
    ]
